version: '3'

services:

  database:
    container_name: database
    image: 'postgres:latest'
    ports:
      - 5432:5432
    env_file:
      - ./backend/.postgres.env

  backend:
    container_name: backend
    build:
      context: ./docker
      dockerfile: backend.dockerfile
    volumes:
      - ./backend:/backend
    depends_on:
      - database
    ports:
      - 8080:8080
    environment:
      - MODE=dev
      - PORT=8080
      - BACKEND_HOST="http://localhost:8080"
      - FRONTEND_HOST="http://localhost:3000"

  frontend:
    container_name: frontend
    build:
      context: ./docker
      dockerfile: frontend.dockerfile
    volumes:
      - ./frontend:/frontend
    ports:
      - 3000:3000
    environment:
      - MODE=dev
      - PORT=3000
