version: '3'

services:

  database:
    image: 'postgres:latest'
    ports:
      - 5432:5432
    env_file:
      - ./backend/.env

  backend:
    image: 'alpine:latest'
    ports:
      - 8080:8080
    env_files:
      - ./backend/.env
    depends_on:
      - database
    volumes:
      - ./backend:/backend
    entrypoint: [""]
