version: '3'

services:

  database:
    container_name: database
    image: 'postgres:latest'
    ports:
      - 5432:5432
    env_file:
      - ./backend/.postgres.env

  backend:
    container_name: backend
    build:
      context: ./docker
      dockerfile: backend.dockerfile
    volumes:
      - ./backend:/backend
    depends_on:
      - database
    ports:
      - 8080:8080
    env_file:
      - ./backend/.env

  frontend:
    container_name: frontend
    build:
      context: ./docker
      dockerfile: frontend.dockerfile
    volumes:
      - ./frontend:/frontend
    depends_on:
      - backend
    ports:
      - 3000:3000
