version: '3'

services:

  database:
    container_name: database
    image: 'postgres:latest'
    ports:
      - 5432:5432
    env_file:
      - ./backend/.env

  backend:
    container_name: backend
    build:
      context: ./docker
      dockerfile: backend.dockerfile
    volumes:
      - ./backend:/backend
    depends_on:
      - database
    ports:
      - 8080:8080
    env_file:
      - ./backend/.env
