#!/bin/bash

usage() {
	echo "./add-user USERNAME PASSWORD"
}

if [ -n "$1" -a -n "$2" ]; then
	docker-compose exec database bash -c "psql -U postgres -d transcendence -c \"INSERT INTO game_user(username,password) VALUES('$1','$2');\""
else
	usage
fi

